### ISSUE TITLE
Brazilian Cases API and Webapp

### ISSUE THREAD

**Issue by endoedgar** [soroushchehresa/awesome-coronavirus#107]
Can you add the Brasil.IO API for CoronaCases and my app?
That API is obtaining city cases by day.

API URL:
https://github.com/turicas/covid19-br

Web App URL:
https://endoedgar.github.io/covid19-monitorbr/

**Comment by soroushchehresa** [comment]
@endoedgar 
Read the [contribution guidelines](https://github.com/soroushchehresa/awesome-coronavirus/blob/master/contributing.md) please.
