### ISSUE TITLE
please rename the repo

### ISSUE THREAD

**Issue by slonik-az** [soroushchehresa/awesome-coronavirus#12]
More appropriate name would be `awful-coronavirus`.

**Comment by rlindskog** [comment]
Might be the perfect name for the repo.

<img width="528" alt="Screen Shot 2020-03-17 at 1 04 23 PM" src="https://user-images.githubusercontent.com/7436773/76896884-eca28380-684f-11ea-8f4e-1a6135e2e6f4.png">

On a more serious not, `aweomse-*` repos are a trend in open source. `aweomse-*` repos are meant for aggregating open-source resources on a particular subject. "awesome" doesn't have anything to do with the nature of the subject its self.

**Comment by soroushchehresa** [comment]
@rlindskog Thanks for your description.  🙏
