### ISSUE TITLE
Add the covid-19 topic

### ISSUE THREAD

**Issue by derekprior** [soroushchehresa/awesome-coronavirus#131]
The covid-19 topic has a good deal of eyes on it currently and seems to be the canonical topic for covid-19 and coronavirus related projects.

**Comment by soroushchehresa** [comment]
@derekprior Yes, I agree with you. 
I created this list because when I was looking for an open-source API about Coronavirus statistics I didn't can find the best repository on GitHub and now this list is so helpful for developers to find the best resources.

**Comment by soroushchehresa** [comment]
@derekprior Yes, I agree with you.
