### ISSUE TITLE
New Resources

### ISSUE THREAD

**Issue by zinlinphyo** [soroushchehresa/awesome-coronavirus#14]
Please add this repos to API 
- https://github.com/NovelCOVID/API
- https://github.com/mathdroid/covid-19-api

This to data and statistics
- https://github.com/opencovid19-fr/data

iOS App
- https://github.com/MhdHejazi/CoronaTracker
- https://github.com/julianschiavo/Covidcheck
- https://github.com/alfianlosari/CoronaVirusTrackerSwiftUI

**Comment by soroushchehresa** [comment]
@zinlinphyo Read the [contribution guidelines](https://github.com/soroushchehresa/awesome-coronavirus/blob/master/contributing.md).
