### ISSUE TITLE
#CodeAgainstCoronavirus

### ISSUE THREAD

**Issue by NotMoni** [soroushchehresa/awesome-coronavirus#144]
Hey, 

We both have to same intention. To Fight Against Coronavirus with Code.
Can you guys link my project to your Repo? 
Could you guys promote my repo as well? 
I feel there are many people working on code to fight COVID-19.
https://github.com/NotMoni/code-against-coronavirus

**Comment by soroushchehresa** [comment]
@NotMoni I don't think your repo has an impressive value for the users.

**Comment by NotMoni** [comment]
@soroushchehresa I will start to get some traction if you could help.
