### ISSUE TITLE
A tool to models COVID-19 outbreak trajectory and hospital demand https://neherlab.org/covid19/

### ISSUE THREAD

**Issue by kgoralski** [soroushchehresa/awesome-coronavirus#15]
A tool to models COVID-19 outbreak trajectory and hospital demand
https://neherlab.org/covid19/
https://github.com/neherlab/covid19_scenarios
found here https://twitter.com/natfriedman/status/1240095856964984833

**Comment by soroushchehresa** [comment]
@kgoralski 
Read the [contribution guidelines](https://github.com/soroushchehresa/awesome-coronavirus/blob/master/contributing.md) please.
