### ISSUE TITLE
Add a list of Hackathons 

### ISSUE THREAD

**Issue by Schnitzel** [soroushchehresa/awesome-coronavirus#167]
Upcoming:
- https://www.en.versusvirus.ch/ #versusvirus (starts 3rd April)
- https://www.hackthecrisis.se/ (3-6 april) 
- https://www.facebook.com/groups/485526048998480 #StudentsAgainstCorona (not sure about dates)

Past:
- https://covid-global-hackathon.devpost.com/ #BuildforCOVID19 (submission deadline is today)
- https://www.codevscovid19.org/ #codevscovid19 (submission deadline today)
- https://www.deutschland.de/en/topic/knowledge/hackathon-on-corona-wirvsvirus-brings-solutions #WirvsVirus (20-22 march)

**Comment by soroushchehresa** [comment]
@Schnitzel Thanks for the suggestion.
Hackathons category added.
https://github.com/soroushchehresa/awesome-coronavirus#hackathons
