### ISSUE TITLE
COVID-19 | Dashboard and Resources

### ISSUE THREAD

**Issue by Biuni** [soroushchehresa/awesome-coronavirus#189]
Hi, I created this website http://covid-19-coronavirus.tools where dashboards and datasets, related to the coronavirus, will be collected. It's a kind of _awesome-coronavirus_ but with a **voting system** and **filter by country**. I think and i hope it will be useful.

_Github repository of the React website: https://github.com/Biuni/covid-19_

**Comment by soroushchehresa** [comment]
@Biuni 
Read the [contribution guidelines](https://github.com/soroushchehresa/awesome-coronavirus/blob/master/contributing.md) please.
