### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by WeileiZeng** [soroushchehresa/awesome-coronavirus#2]
Hi I have a similar list.

https://weileizeng.github.io/Open-Source-COVID-19/

My list start from china-based project, which is very comprehensive. The world page just start recently, and I classify it by areas/countries. I like your classification as well. Looking forward for collaborations!

I have been working for weeks, and now can only maintain the list passively now, waiting for submissions. It would be great if we can just merge our list together, and I can add your way of classification in a separate page. How about that?

**Comment by WeileiZeng** [comment]
https://github.com/ThomasThelen/awesome-coronavirus

This is a great list as well. @ThomasThelen 

My website got around 300-500 page views per day, which would be a good starting point. Also, the users doesn't need to go through several different list for information.

**Comment by WeileiZeng** [comment]
https://github.com/WeileiZeng/Open-Source-COVID-19/blob/master/_data/world.yml

My idea is to rearrange this data file. For each entry/project/repository, I will add some tags, including country, functions, focus, etc. Then we can list it in whatever way we want. I think this is a flexible format to incorporate different perspectives on classification.

**Comment by WeileiZeng** [comment]
I notice you also have a lot of non open source projects in your list. My list may only overlap with the open sourced ones.

**Comment by ThomasThelen** [comment]
YAML should be approachable for enough people to get use out of it and tags will definitely make it more interesting, from a user standpoint.

Use Case A:
A user wants to find all of the projects in The Unites States that has a focus on public health outreach.

It's probably a good idea to keep the tags fairly abstract or you'll spend days designing a schema around coronavirus tags.

**Comment by soroushchehresa** [comment]
I think listing the data in the readme of a project on GitHub is the best way.
However, I placed list data in `data/` directory as JSON files that everyone can use them.

**Comment by soroushchehresa** [comment]
@WeileiZeng  @ThomasThelen 
Thanks for your attention 🙏

**Comment by WeileiZeng** [comment]
My data is in _data/*.json as well.

**Comment by WeileiZeng** [comment]
https://github.com/WeileiZeng/Open-Source-COVID-19/tree/master/_data

**Comment by WeileiZeng** [comment]
> My data is in _data/*.json as well.

I am actually using yaml. Will save a json copy upon requested.
