### ISSUE TITLE
https://pypi.org/project/pandemic/

### ISSUE THREAD

**Issue by microprediction** [soroushchehresa/awesome-coronavirus#236]
https://pypi.org/project/pandemic/

**Comment by soroushchehresa** [comment]
@microprediction 
Please provide more information.

**Comment by microprediction** [comment]
It is an open source python model for simulation of pandemics 


Sent with BlackBerry Work
(www.blackberry.com)

**Comment by soroushchehresa** [comment]
@microprediction 
Thanks! added to the models section.
