### ISSUE TITLE
hardware?

### ISSUE THREAD

**Issue by tomByrer** [soroushchehresa/awesome-coronavirus#24]
I'm not sure where to put this forum.
It is for 3d printing files, locations, tips, etc for medical supplies.

But NOT all are truly 'open source', in [related article](https://www.3dprintingmedia.network/covid-19-3d-printed-valve-for-reanimation-device/) what 1 city was printing 'remains covered by copyright and patents. Hospitals may have a right to produce these parts in an emergency'.  So not really 'open source', per se....
But either way, a great resource.

https://www.3dprintingmedia.network/3d-printing-unite-for-covid-19/

**Comment by soroushchehresa** [comment]
@tomByrer I don't think it's related to this list.
However thanks for the suggestion!
