### ISSUE TITLE
Topic labels: coronavirus, covid-19, 2019-ncov

### ISSUE THREAD

**Issue by westurner** [soroushchehresa/awesome-coronavirus#252]
- [ ] Additional topic labels for this gh project:
  - coronavirus
  - covid-19
  - covid19
  - 2019-ncov
  - sars-cov-2
  - epidemiology
- [ ] The README could link to said labels (and encourage use of said labels) as well
  - https://github.com/topics/coronavirus
  - https://github.com/topics/covid-19
  - https://github.com/topics/covid19
  - https://github.com/topics/2019-ncov
  - https://github.com/topics/sars-cov-2
  - https://github.com/topics/epidemiology
- Maybe link to [Twitter,] hashtags, too?
  - https://twitter.com/search?q=coronavirus
  - https://twitter.com/search?q=covid19
  - https://twitter.com/search?q=2019-ncov
  - https://twitter.com/search?q=sars-cov-2
  - https://twitter.com/search?q=epidemiology

**Comment by soroushchehresa** [comment]
@westurner 
Thanks!

**Comment by westurner** [comment]
For what? I notice that you checked these

Not sure where you to add them
