### ISSUE TITLE
COVID-19 Mobile app for South Africa.

### ISSUE THREAD

**Issue by shaunsaker** [soroushchehresa/awesome-coronavirus#253]
https://github.com/shaunsaker/covid-19-south-africa-app

Notifies users of the latest confirmed cases and displays the stats (confirmed cases, recoveries, tests and deaths) in a graph view.

Thanks for your list :)

**Comment by soroushchehresa** [comment]
@shaunsaker 
Read the [contribution guidelines](https://github.com/soroushchehresa/awesome-coronavirus/blob/master/contributing.md) and then add your project under `Open Source Projects`/`Applications and Bots`.

**Recommendation**
Add some screenshot of the app in the repository's readme!

**Comment by shaunsaker** [comment]
@soroushchehresa Aha, thanks so much, will do.
