### ISSUE TITLE
Add FOSS Responders

### ISSUE THREAD

**Issue by RichardLitt** [soroushchehresa/awesome-coronavirus#272]
I'd like to add [FOSS Responders](https://fossresponders.com). It's a site to connect devs or projects that have been affected by Covid-19 with funds to help them out. 

I can't figure out the right place to put this, though. It's kind of a meta-project. Any ideas?

**Comment by soroushchehresa** [comment]
Add the website under `Applications`/`Web Apps`.

[Contribution Guidelines](https://github.com/soroushchehresa/awesome-coronavirus/blob/master/contributing.md)
