### ISSUE TITLE
Ask for add PocovidScreen

### ISSUE THREAD

**Issue by stat1x** [soroushchehresa/awesome-coronavirus#310]
Hi, 
Thanks for this great library of projects.
We did a website during previous hackathons that can detect COVID-19 from POCUS images. 
I think it would be great if you can add it to the "Web applications" section.

Here is the link :
https://pocovidscreen.org/

Here is the name :
PocovidScreen 

Here is the description :
An AI tool for early screening of COVID-19 & pneumonia from ultrasound recordings (POCUS)

**Comment by soroushchehresa** [comment]
@stat1x Hi, Thanks for the suggestion. 
The item just added.
