### ISSUE TITLE
Add Alert Covid-19

### ISSUE THREAD

**Issue by renanbastos93** [soroushchehresa/awesome-coronavirus#325]
Alert COVID-19 is a small multiplatform tool written in Golang to help keep you informed about the current situation of COVID-19 in your region, while you stay safe at home.

https://github.com/renanbastos93/alertcovid19

**Comment by soroushchehresa** [comment]
Read the [contribution guidelines](https://github.com/soroushchehresa/awesome-coronavirus/blob/master/contributing.md) please.
