### ISSUE TITLE
Perhaps add my covid python package

### ISSUE THREAD

**Issue by ahmednafies** [soroushchehresa/awesome-coronavirus#350]
[https://github.com/ahmednafies/covid](https://github.com/ahmednafies/covid)

it has around 68,000 downloads so far
and here is the documentation as well.

[https://ahmednafies.github.io/covid/](https://ahmednafies.github.io/covid/)

**Comment by soroushchehresa** [comment]
@ahmednafies  Read the [contribution guidelines](https://github.com/soroushchehresa/awesome-coronavirus/blob/master/contributing.md) please.
