### ISSUE TITLE
[Discussion] Rename repository

### ISSUE THREAD

**Issue by karx** [soroushchehresa/awesome-coronavirus#353]
Can we rename this repository to something other than _awesome_ coronavirus.

Let's be honest here, the repo is an awesome resource link, true, but this _virus thing_ is not.
The term _awesome_ does not necessarily needs to be in an awesome-list. 

Here are a few examples of awesome lists without the term *awesome* to support the motion.
* https://github.com/bolshchikov/js-must-watch
* https://github.com/maxogden/maintenance-modules
* https://github.com/lvwzhen/tools
* https://github.com/edobashira/speech-language-processing
 

`PS: @maintainers I could just be saltly quarantined for so long. Thus added that discussion tag.`

**Comment by soroushchehresa** [comment]
@karx Please read [this comment](https://github.com/soroushchehresa/awesome-coronavirus/issues/12#issuecomment-600272828).
