### ISSUE TITLE
90,000 covid github projects

### ISSUE THREAD

**Issue by estaub** [soroushchehresa/awesome-coronavirus#359]
You probably want to know about this, probably want to post it too.
https://github.com/github/covid-19-repo-data

**Comment by soroushchehresa** [comment]
@estaub 
Read the [contribution guidelines](https://github.com/soroushchehresa/awesome-coronavirus/blob/master/contributing.md) please.

**Comment by estaub** [comment]
Because the github project list is so broad in nature, it does not fit within any of your existing categories, so I cannot comply with your guidelines.  Some big data repositories are there, some apps, one is a collection of obituaries.  You may want to add another category to cross-reference other wide lists of resources like your own.  To get a quick idea of what's there, you might look at this page I put up: https://estaub.github.io/covid-project-report/  .
