### ISSUE TITLE
I have created an web app to track Corona virus primarily for India 

### ISSUE THREAD

**Issue by akashrajum7** [soroushchehresa/awesome-coronavirus#37]
It can be accessed from this link: https://corona-tracker-2020.netlify.com/ and source code of that project is available here: https://github.com/akashrajum7/corona-tracker.

I would love for it to be added to the list.

Thank you.

**Comment by soroushchehresa** [comment]
@akashrajum7 Read the [contribution guidelines](https://github.com/soroushchehresa/awesome-coronavirus/blob/master/contributing.md) please.

**Comment by akashrajum7** [comment]
@soroushchehresa I have created a pull request, thank you.
