### ISSUE TITLE
Table for Testing and Vaccination

### ISSUE THREAD

**Issue by inavamsi** [soroushchehresa/awesome-coronavirus#412]
Due to various types of testing ranging from RT-PCR to Antibody testing. There is also new types of efficient testing called Pool testing with which we can test more people with fewer tests.

Similarly there are various types of vaccines and efficacy. 

This table will contain : Url's to different types of tests and vaccines based on company producing them.

**Comment by soroushchehresa** [comment]
@inavamsi Thank you for this issue.
[Vaccination section](https://github.com/soroushchehresa/awesome-coronavirus#vaccination) just added.
