### ISSUE TITLE
COVID-19 European Regional Tracker

### ISSUE THREAD

**Issue by asjadnaqvi** [soroushchehresa/awesome-coronavirus#425]
Dear all, I just came across this amazing COVID-19 resource page. Thank you for putting this together!

I have my own data tracker here that collects data at the NUTS regional level for Europe:
https://github.com/asjadnaqvi/COVID19-European-Regional-Tracker

The data is also published now:
https://www.nature.com/articles/s41597-021-00950-7

It will be great if it can be added to the list as well.

Best wishes,
Asjad

**Comment by soroushchehresa** [comment]
@asjadnaqvi
Read the [contribution guidelines](https://github.com/soroushchehresa/awesome-coronavirus/blob/master/contributing.md) please.
