### ISSUE TITLE
Dynamic stars

### ISSUE THREAD

**Issue by modaresimr** [soroushchehresa/awesome-coronavirus#430]
you can use dynamic star counts instead of static one. e.g., for neherlab/covid19_scenarios repository you can put this
```
[![stars](https://img.shields.io/github/stars/neherlab/covid19_scenarios?label=%F0%9F%8C%9F)](https://GitHub.com/neherlab/covid19_scenarios)

```
e.g., 
| 🌟     | Repository   | Description  |
|:-----------:|:-------------|:-------------|
 | [![stars](https://img.shields.io/github/stars/neherlab/covid19_scenarios?label=%F0%9F%8C%9F)](https://GitHub.com/neherlab/covid19_scenarios) | [@neherlab](https://github.com/neherlab)/[**covid19_scenarios**](https://github.com/neherlab/covid19_scenarios) | Models of COVID-19 outbreak trajectories and hospital demand |

[more info](https://naereen.github.io/badges/)

**Comment by soroushchehresa** [comment]
@modaresimr Thanks for the suggestion,
But the stars count is not fully static and will be updated every two days by Travis CI.
