### ISSUE TITLE
COVID19 API

### ISSUE THREAD

**Issue by ChrisMichaelPerezSantiago** [soroushchehresa/awesome-coronavirus#53]
_Hi friends_

_First of all ..._
_I greatly appreciate the effort you are making to make the publications of the different api that provide information from the COVID19_

_Several days ago, I created an api that you might be interested in and added to the api list, for the benefit of devs._

URL [COVID19 API](https://github.com/ChrisMichaelPerezSantiago/covid19)

**Comment by soroushchehresa** [comment]
@ChrisMichaelPerezSantiago Thanks for your kind words.
For adding this repository to the list, please read the [contribution guidelines]((https://github.com/soroushchehresa/awesome-coronavirus/blob/master/contributing.md)) first.
