### ISSUE TITLE
Merge with adamdriscoll/awesome-covid19-resources

### ISSUE THREAD

**Issue by 0x2b3bfa0** [soroushchehresa/awesome-coronavirus#54]
There is a similar repository at https://github.com/adamdriscoll/awesome-covid19-resources

**Comment by soroushchehresa** [comment]
@0x2b3bfa0 I don't think this repository has an impressive value for GitHub users that can merge with `awesome-coronavirus`. However thanks for the suggestion.

**Comment by 0x2b3bfa0** [comment]
After reviewing its contents, I realized so. Thanks for your prompt reply!
